dist: xenial
language: clojure
lein: 2.8.1
cache:
  directories:
    - $HOME/.m2
script:
  - make $TARGET
env:
  matrix:
    - VERSION=1.7 TARGET=test
    - VERSION=1.8 TARGET=test
    - VERSION=1.9 TARGET=test
    - VERSION=1.10 TARGET=test
    - VERSION=master TARGET=test
  global:
    # deployment credentials
    - secure: "f2pEAipCOs8JRMzSVMnbqBPbWFzI7G/FjPW9FY9ZjAhRvpslRC6JzG4r6uSJMoKU474ZQk+hzpYXCNSuqbztvYdd50J7E5iT3SpOIpRkNHtao0kEfxzFlH7P+sQ0LWPU5KZJXMue/9lKLxXdersdl2SAU7PSntQwqTEEicMluYs="
    - secure: "PheOCJixQP9LaDcmkHGAOLmmPG6AQyN+PkgYw23cDTcFA6FKh4uVj28PHhlCQc0V6KrwzDqUAoSzyhSlcGm6LiZks714w6WHL3jpfIxnVKHN0J8FktnCy9Td9nrKhBCC2kNisaEhRyK4LojDcdFpliXZjJoituDnp4YhnaRIpsw="
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
stages:
  - name: check
    jdk: openjdk11
  - name: test
  - name: deploy
    jdk: openjdk11
    # Deploy only from the home repo where the credentials can be
    # properly decrypted. Never deploy from a pull request job.
    # In addition, ensure we're on the master branch (snapshots)
    # or a branch with semver naming (releases).
    if: repo = nrepl/nrepl
        AND type != pull_request
        AND ( branch = master OR branch =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ )
jobs:
  include:
    - stage: check
      env: VERSION=1.10 TARGET=eastwood

    - stage: check
      env: VERSION=1.10 TARGET=cljfmt

    - stage: check
      env: VERSION=1.10 TARGET=verify_cljdoc

    - stage: test
      env: VERSION=1.10 TARGET=cloverage
      jdk: openjdk8
      after_success: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

    - stage: deploy
      env: TARGET=deploy

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
    - env: VERSION=master TARGET=test
    - env: VERSION=1.10 TARGET=cloverage
